#!/bin/bash

# Origin-side firewall filter rules.
# with these rules, any attack bypassing Beetware CDN and commencing through origin server will be dropped by iptables.
# Run this BASH script on your host.
# NOTE: Setting this script as cron is recommended.

systemctl restart iptables
systemctl enable iptables

iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X

for i in `curl https://raw.githubusercontent.com/beetware/beetwarePublic/master/ipv4list.txt`; do
  echo "[i] IPv4 $i whitelisted."
  iptables -I INPUT -p tcp -m multiport --dports http,https -s $i -j ACCEPT;
done

for i in `curl https://raw.githubusercontent.com/beetware/beetwarePublic/master/ipv6list.txt`; do 
  echo "[i] IPv6 $i whitelisted."
  ip6tables -I INPUT -p tcp -m multiport --dports http,https -s $i -j ACCEPT;
done

iptables -A INPUT -p tcp -m multiport --dports http,https -j DROP
ip6tables -A INPUT -p tcp -m multiport --dports http,https -j DROP
service iptables save
iptables-save
